version: '2'

services:
  zkcluster-db:
    image: postgres:10.1-alpine
    container_name: zkcluster-db
    volumes:
      - zk_postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${PGDATABASE}
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
#    ports:
#      - "54321:5432"
    restart: always
  zkcluster:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: zkcluster:1.0.0
    container_name: zkcluster
    command: bash -c "python /code/manage.py migrate --noinput && python /code/manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    env_file: .env
    volumes:
      - ../zkcluster:/code/zkcluster
    depends_on:
      - zkcluster-db

volumes:
  zk_postgres_data:
